services:
  - type: web
    name: crazyshop-ecommerce-store
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false